### ISSUE TITLE
这是啥情况？

### ISSUE THREAD

**Issue by xcja123** [woshimanong1990/image_to_pdf#1]
![image](https://user-images.githubusercontent.com/34464154/99756327-db6ced80-2b27-11eb-9040-a993e812cbb9.png)

**Comment by xcja123** [comment]
2020-11-20 11:31:45 root         ERROR    startCreate
Traceback (most recent call last):
  File "site-packages\PIL\Image.py", line 1930, in save
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "image_to_pdf\main_window.py", line 128, in startCreate
  File "image_to_pdf\main_window.py", line 114, in cover_to_pdf
  File "site-packages\PIL\Image.py", line 1932, in save
ValueError: unknown file extension:
